package com.emrubik.rose.generator.dao;

import com.emrubik.rose.generator.dao.bean.EmplyeePo;
import com.emrubik.rose.generator.dao.bean.EmplyeePoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmplyeePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int countByExample(EmplyeePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int deleteByExample(EmplyeePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int insert(EmplyeePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int insertSelective(EmplyeePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    List<EmplyeePo> selectByExample(EmplyeePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EmplyeePo record, @Param("example") EmplyeePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_EMPLOYEE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EmplyeePo record, @Param("example") EmplyeePoExample example);
}