package com.emrubik.rose.generator.dao;

import com.emrubik.rose.generator.dao.bean.RoseWorkflowPo;
import com.emrubik.rose.generator.dao.bean.RoseWorkflowPoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoseWorkflowPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int countByExample(RoseWorkflowPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int deleteByExample(RoseWorkflowPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int insert(RoseWorkflowPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int insertSelective(RoseWorkflowPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    List<RoseWorkflowPo> selectByExample(RoseWorkflowPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoseWorkflowPo record, @Param("example") RoseWorkflowPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoseWorkflowPo record, @Param("example") RoseWorkflowPoExample example);
}