package com.emrubik.rose.generator.dao.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeptPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public DeptPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("OID is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("OID is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(BigDecimal value) {
            addCriterion("OID =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(BigDecimal value) {
            addCriterion("OID <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(BigDecimal value) {
            addCriterion("OID >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OID >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(BigDecimal value) {
            addCriterion("OID <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OID <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<BigDecimal> values) {
            addCriterion("OID in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<BigDecimal> values) {
            addCriterion("OID not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OID between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OID not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DEPTID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DEPTID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DEPTID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DEPTID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DEPTID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DEPTID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DEPTID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DEPTID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DEPTID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DEPTID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DEPTID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("DEPT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("DEPT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("DEPT_NAME =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("DEPT_NAME <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("DEPT_NAME >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_NAME >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("DEPT_NAME <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("DEPT_NAME <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("DEPT_NAME like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("DEPT_NAME not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("DEPT_NAME in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("DEPT_NAME not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("DEPT_NAME between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("DEPT_NAME not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andEffdtIsNull() {
            addCriterion("EFFDT is null");
            return (Criteria) this;
        }

        public Criteria andEffdtIsNotNull() {
            addCriterion("EFFDT is not null");
            return (Criteria) this;
        }

        public Criteria andEffdtEqualTo(Date value) {
            addCriterion("EFFDT =", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotEqualTo(Date value) {
            addCriterion("EFFDT <>", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtGreaterThan(Date value) {
            addCriterion("EFFDT >", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtGreaterThanOrEqualTo(Date value) {
            addCriterion("EFFDT >=", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtLessThan(Date value) {
            addCriterion("EFFDT <", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtLessThanOrEqualTo(Date value) {
            addCriterion("EFFDT <=", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtIn(List<Date> values) {
            addCriterion("EFFDT in", values, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotIn(List<Date> values) {
            addCriterion("EFFDT not in", values, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtBetween(Date value1, Date value2) {
            addCriterion("EFFDT between", value1, value2, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotBetween(Date value1, Date value2) {
            addCriterion("EFFDT not between", value1, value2, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIsNull() {
            addCriterion("EFFDT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIsNotNull() {
            addCriterion("EFFDT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusEqualTo(String value) {
            addCriterion("EFFDT_STATUS =", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotEqualTo(String value) {
            addCriterion("EFFDT_STATUS <>", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusGreaterThan(String value) {
            addCriterion("EFFDT_STATUS >", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusGreaterThanOrEqualTo(String value) {
            addCriterion("EFFDT_STATUS >=", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLessThan(String value) {
            addCriterion("EFFDT_STATUS <", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLessThanOrEqualTo(String value) {
            addCriterion("EFFDT_STATUS <=", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLike(String value) {
            addCriterion("EFFDT_STATUS like", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotLike(String value) {
            addCriterion("EFFDT_STATUS not like", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIn(List<String> values) {
            addCriterion("EFFDT_STATUS in", values, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotIn(List<String> values) {
            addCriterion("EFFDT_STATUS not in", values, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusBetween(String value1, String value2) {
            addCriterion("EFFDT_STATUS between", value1, value2, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotBetween(String value1, String value2) {
            addCriterion("EFFDT_STATUS not between", value1, value2, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNull() {
            addCriterion("MANAGER_ID is null");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNotNull() {
            addCriterion("MANAGER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andManagerIdEqualTo(String value) {
            addCriterion("MANAGER_ID =", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotEqualTo(String value) {
            addCriterion("MANAGER_ID <>", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThan(String value) {
            addCriterion("MANAGER_ID >", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThanOrEqualTo(String value) {
            addCriterion("MANAGER_ID >=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThan(String value) {
            addCriterion("MANAGER_ID <", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThanOrEqualTo(String value) {
            addCriterion("MANAGER_ID <=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLike(String value) {
            addCriterion("MANAGER_ID like", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotLike(String value) {
            addCriterion("MANAGER_ID not like", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdIn(List<String> values) {
            addCriterion("MANAGER_ID in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotIn(List<String> values) {
            addCriterion("MANAGER_ID not in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdBetween(String value1, String value2) {
            addCriterion("MANAGER_ID between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotBetween(String value1, String value2) {
            addCriterion("MANAGER_ID not between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerNameIsNull() {
            addCriterion("MANAGER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andManagerNameIsNotNull() {
            addCriterion("MANAGER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andManagerNameEqualTo(String value) {
            addCriterion("MANAGER_NAME =", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameNotEqualTo(String value) {
            addCriterion("MANAGER_NAME <>", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameGreaterThan(String value) {
            addCriterion("MANAGER_NAME >", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameGreaterThanOrEqualTo(String value) {
            addCriterion("MANAGER_NAME >=", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameLessThan(String value) {
            addCriterion("MANAGER_NAME <", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameLessThanOrEqualTo(String value) {
            addCriterion("MANAGER_NAME <=", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameLike(String value) {
            addCriterion("MANAGER_NAME like", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameNotLike(String value) {
            addCriterion("MANAGER_NAME not like", value, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameIn(List<String> values) {
            addCriterion("MANAGER_NAME in", values, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameNotIn(List<String> values) {
            addCriterion("MANAGER_NAME not in", values, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameBetween(String value1, String value2) {
            addCriterion("MANAGER_NAME between", value1, value2, "managerName");
            return (Criteria) this;
        }

        public Criteria andManagerNameNotBetween(String value1, String value2) {
            addCriterion("MANAGER_NAME not between", value1, value2, "managerName");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelIsNull() {
            addCriterion("U_DEPT_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelIsNotNull() {
            addCriterion("U_DEPT_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelEqualTo(String value) {
            addCriterion("U_DEPT_LEVEL =", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelNotEqualTo(String value) {
            addCriterion("U_DEPT_LEVEL <>", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelGreaterThan(String value) {
            addCriterion("U_DEPT_LEVEL >", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelGreaterThanOrEqualTo(String value) {
            addCriterion("U_DEPT_LEVEL >=", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelLessThan(String value) {
            addCriterion("U_DEPT_LEVEL <", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelLessThanOrEqualTo(String value) {
            addCriterion("U_DEPT_LEVEL <=", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelLike(String value) {
            addCriterion("U_DEPT_LEVEL like", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelNotLike(String value) {
            addCriterion("U_DEPT_LEVEL not like", value, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelIn(List<String> values) {
            addCriterion("U_DEPT_LEVEL in", values, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelNotIn(List<String> values) {
            addCriterion("U_DEPT_LEVEL not in", values, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelBetween(String value1, String value2) {
            addCriterion("U_DEPT_LEVEL between", value1, value2, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUDeptLevelNotBetween(String value1, String value2) {
            addCriterion("U_DEPT_LEVEL not between", value1, value2, "uDeptLevel");
            return (Criteria) this;
        }

        public Criteria andUpOidIsNull() {
            addCriterion("UP_OID is null");
            return (Criteria) this;
        }

        public Criteria andUpOidIsNotNull() {
            addCriterion("UP_OID is not null");
            return (Criteria) this;
        }

        public Criteria andUpOidEqualTo(BigDecimal value) {
            addCriterion("UP_OID =", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidNotEqualTo(BigDecimal value) {
            addCriterion("UP_OID <>", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidGreaterThan(BigDecimal value) {
            addCriterion("UP_OID >", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UP_OID >=", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidLessThan(BigDecimal value) {
            addCriterion("UP_OID <", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UP_OID <=", value, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidIn(List<BigDecimal> values) {
            addCriterion("UP_OID in", values, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidNotIn(List<BigDecimal> values) {
            addCriterion("UP_OID not in", values, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UP_OID between", value1, value2, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpOidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UP_OID not between", value1, value2, "upOid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidIsNull() {
            addCriterion("UP_DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andUpDeptidIsNotNull() {
            addCriterion("UP_DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andUpDeptidEqualTo(String value) {
            addCriterion("UP_DEPTID =", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidNotEqualTo(String value) {
            addCriterion("UP_DEPTID <>", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidGreaterThan(String value) {
            addCriterion("UP_DEPTID >", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("UP_DEPTID >=", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidLessThan(String value) {
            addCriterion("UP_DEPTID <", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidLessThanOrEqualTo(String value) {
            addCriterion("UP_DEPTID <=", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidLike(String value) {
            addCriterion("UP_DEPTID like", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidNotLike(String value) {
            addCriterion("UP_DEPTID not like", value, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidIn(List<String> values) {
            addCriterion("UP_DEPTID in", values, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidNotIn(List<String> values) {
            addCriterion("UP_DEPTID not in", values, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidBetween(String value1, String value2) {
            addCriterion("UP_DEPTID between", value1, value2, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUpDeptidNotBetween(String value1, String value2) {
            addCriterion("UP_DEPTID not between", value1, value2, "upDeptid");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureIsNull() {
            addCriterion("U_DEPT_NATURE is null");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureIsNotNull() {
            addCriterion("U_DEPT_NATURE is not null");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureEqualTo(String value) {
            addCriterion("U_DEPT_NATURE =", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureNotEqualTo(String value) {
            addCriterion("U_DEPT_NATURE <>", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureGreaterThan(String value) {
            addCriterion("U_DEPT_NATURE >", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureGreaterThanOrEqualTo(String value) {
            addCriterion("U_DEPT_NATURE >=", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureLessThan(String value) {
            addCriterion("U_DEPT_NATURE <", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureLessThanOrEqualTo(String value) {
            addCriterion("U_DEPT_NATURE <=", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureLike(String value) {
            addCriterion("U_DEPT_NATURE like", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureNotLike(String value) {
            addCriterion("U_DEPT_NATURE not like", value, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureIn(List<String> values) {
            addCriterion("U_DEPT_NATURE in", values, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureNotIn(List<String> values) {
            addCriterion("U_DEPT_NATURE not in", values, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureBetween(String value1, String value2) {
            addCriterion("U_DEPT_NATURE between", value1, value2, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andUDeptNatureNotBetween(String value1, String value2) {
            addCriterion("U_DEPT_NATURE not between", value1, value2, "uDeptNature");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNull() {
            addCriterion("CREATIONTIME is null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNotNull() {
            addCriterion("CREATIONTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeEqualTo(Date value) {
            addCriterion("CREATIONTIME =", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotEqualTo(Date value) {
            addCriterion("CREATIONTIME <>", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThan(Date value) {
            addCriterion("CREATIONTIME >", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME >=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThan(Date value) {
            addCriterion("CREATIONTIME <", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME <=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIn(List<Date> values) {
            addCriterion("CREATIONTIME in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotIn(List<Date> values) {
            addCriterion("CREATIONTIME not in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME not between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNull() {
            addCriterion("MODTIME is null");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNotNull() {
            addCriterion("MODTIME is not null");
            return (Criteria) this;
        }

        public Criteria andModtimeEqualTo(Date value) {
            addCriterion("MODTIME =", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotEqualTo(Date value) {
            addCriterion("MODTIME <>", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThan(Date value) {
            addCriterion("MODTIME >", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODTIME >=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThan(Date value) {
            addCriterion("MODTIME <", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThanOrEqualTo(Date value) {
            addCriterion("MODTIME <=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeIn(List<Date> values) {
            addCriterion("MODTIME in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotIn(List<Date> values) {
            addCriterion("MODTIME not in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeBetween(Date value1, Date value2) {
            addCriterion("MODTIME between", value1, value2, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotBetween(Date value1, Date value2) {
            addCriterion("MODTIME not between", value1, value2, "modtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameIsNull() {
            addCriterion("DEPT_ALLNAME is null");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameIsNotNull() {
            addCriterion("DEPT_ALLNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameEqualTo(String value) {
            addCriterion("DEPT_ALLNAME =", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameNotEqualTo(String value) {
            addCriterion("DEPT_ALLNAME <>", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameGreaterThan(String value) {
            addCriterion("DEPT_ALLNAME >", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ALLNAME >=", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameLessThan(String value) {
            addCriterion("DEPT_ALLNAME <", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ALLNAME <=", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameLike(String value) {
            addCriterion("DEPT_ALLNAME like", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameNotLike(String value) {
            addCriterion("DEPT_ALLNAME not like", value, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameIn(List<String> values) {
            addCriterion("DEPT_ALLNAME in", values, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameNotIn(List<String> values) {
            addCriterion("DEPT_ALLNAME not in", values, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameBetween(String value1, String value2) {
            addCriterion("DEPT_ALLNAME between", value1, value2, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andDeptAllnameNotBetween(String value1, String value2) {
            addCriterion("DEPT_ALLNAME not between", value1, value2, "deptAllname");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNull() {
            addCriterion("GROUP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNotNull() {
            addCriterion("GROUP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNameEqualTo(String value) {
            addCriterion("GROUP_NAME =", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotEqualTo(String value) {
            addCriterion("GROUP_NAME <>", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThan(String value) {
            addCriterion("GROUP_NAME >", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_NAME >=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThan(String value) {
            addCriterion("GROUP_NAME <", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThanOrEqualTo(String value) {
            addCriterion("GROUP_NAME <=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLike(String value) {
            addCriterion("GROUP_NAME like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotLike(String value) {
            addCriterion("GROUP_NAME not like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameIn(List<String> values) {
            addCriterion("GROUP_NAME in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotIn(List<String> values) {
            addCriterion("GROUP_NAME not in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameBetween(String value1, String value2) {
            addCriterion("GROUP_NAME between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotBetween(String value1, String value2) {
            addCriterion("GROUP_NAME not between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andOuIsNull() {
            addCriterion("OU is null");
            return (Criteria) this;
        }

        public Criteria andOuIsNotNull() {
            addCriterion("OU is not null");
            return (Criteria) this;
        }

        public Criteria andOuEqualTo(String value) {
            addCriterion("OU =", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuNotEqualTo(String value) {
            addCriterion("OU <>", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuGreaterThan(String value) {
            addCriterion("OU >", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuGreaterThanOrEqualTo(String value) {
            addCriterion("OU >=", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuLessThan(String value) {
            addCriterion("OU <", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuLessThanOrEqualTo(String value) {
            addCriterion("OU <=", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuLike(String value) {
            addCriterion("OU like", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuNotLike(String value) {
            addCriterion("OU not like", value, "ou");
            return (Criteria) this;
        }

        public Criteria andOuIn(List<String> values) {
            addCriterion("OU in", values, "ou");
            return (Criteria) this;
        }

        public Criteria andOuNotIn(List<String> values) {
            addCriterion("OU not in", values, "ou");
            return (Criteria) this;
        }

        public Criteria andOuBetween(String value1, String value2) {
            addCriterion("OU between", value1, value2, "ou");
            return (Criteria) this;
        }

        public Criteria andOuNotBetween(String value1, String value2) {
            addCriterion("OU not between", value1, value2, "ou");
            return (Criteria) this;
        }

        public Criteria andOuNameIsNull() {
            addCriterion("OU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOuNameIsNotNull() {
            addCriterion("OU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOuNameEqualTo(String value) {
            addCriterion("OU_NAME =", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameNotEqualTo(String value) {
            addCriterion("OU_NAME <>", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameGreaterThan(String value) {
            addCriterion("OU_NAME >", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameGreaterThanOrEqualTo(String value) {
            addCriterion("OU_NAME >=", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameLessThan(String value) {
            addCriterion("OU_NAME <", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameLessThanOrEqualTo(String value) {
            addCriterion("OU_NAME <=", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameLike(String value) {
            addCriterion("OU_NAME like", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameNotLike(String value) {
            addCriterion("OU_NAME not like", value, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameIn(List<String> values) {
            addCriterion("OU_NAME in", values, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameNotIn(List<String> values) {
            addCriterion("OU_NAME not in", values, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameBetween(String value1, String value2) {
            addCriterion("OU_NAME between", value1, value2, "ouName");
            return (Criteria) this;
        }

        public Criteria andOuNameNotBetween(String value1, String value2) {
            addCriterion("OU_NAME not between", value1, value2, "ouName");
            return (Criteria) this;
        }

        public Criteria andPsDeptidIsNull() {
            addCriterion("PS_DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andPsDeptidIsNotNull() {
            addCriterion("PS_DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andPsDeptidEqualTo(String value) {
            addCriterion("PS_DEPTID =", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidNotEqualTo(String value) {
            addCriterion("PS_DEPTID <>", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidGreaterThan(String value) {
            addCriterion("PS_DEPTID >", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("PS_DEPTID >=", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidLessThan(String value) {
            addCriterion("PS_DEPTID <", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidLessThanOrEqualTo(String value) {
            addCriterion("PS_DEPTID <=", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidLike(String value) {
            addCriterion("PS_DEPTID like", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidNotLike(String value) {
            addCriterion("PS_DEPTID not like", value, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidIn(List<String> values) {
            addCriterion("PS_DEPTID in", values, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidNotIn(List<String> values) {
            addCriterion("PS_DEPTID not in", values, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidBetween(String value1, String value2) {
            addCriterion("PS_DEPTID between", value1, value2, "psDeptid");
            return (Criteria) this;
        }

        public Criteria andPsDeptidNotBetween(String value1, String value2) {
            addCriterion("PS_DEPTID not between", value1, value2, "psDeptid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_DEPT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}