package com.emrubik.rose.generator.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PS_I_DEPT
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class DeptPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.OID
     *
     * @mbggenerated
     */
    private BigDecimal oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.DEPTID
     *
     * @mbggenerated
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.DEPT_NAME
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.EFFDT
     *
     * @mbggenerated
     */
    private Date effdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.EFFDT_STATUS
     *
     * @mbggenerated
     */
    private String effdtStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.MANAGER_ID
     *
     * @mbggenerated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.MANAGER_NAME
     *
     * @mbggenerated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.U_DEPT_LEVEL
     *
     * @mbggenerated
     */
    private String uDeptLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.UP_OID
     *
     * @mbggenerated
     */
    private BigDecimal upOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.UP_DEPTID
     *
     * @mbggenerated
     */
    private String upDeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.U_DEPT_NATURE
     *
     * @mbggenerated
     */
    private String uDeptNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.CREATIONTIME
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.MODTIME
     *
     * @mbggenerated
     */
    private Date modtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.DEPT_ALLNAME
     *
     * @mbggenerated
     */
    private String deptAllname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.OU
     *
     * @mbggenerated
     */
    private String ou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.OU_NAME
     *
     * @mbggenerated
     */
    private String ouName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_DEPT.PS_DEPTID
     *
     * @mbggenerated
     */
    private String psDeptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.OID
     *
     * @return the value of PS_I_DEPT.OID
     *
     * @mbggenerated
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.OID
     *
     * @param oid the value for PS_I_DEPT.OID
     *
     * @mbggenerated
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.DEPTID
     *
     * @return the value of PS_I_DEPT.DEPTID
     *
     * @mbggenerated
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.DEPTID
     *
     * @param deptid the value for PS_I_DEPT.DEPTID
     *
     * @mbggenerated
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.DEPT_NAME
     *
     * @return the value of PS_I_DEPT.DEPT_NAME
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.DEPT_NAME
     *
     * @param deptName the value for PS_I_DEPT.DEPT_NAME
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.EFFDT
     *
     * @return the value of PS_I_DEPT.EFFDT
     *
     * @mbggenerated
     */
    public Date getEffdt() {
        return effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.EFFDT
     *
     * @param effdt the value for PS_I_DEPT.EFFDT
     *
     * @mbggenerated
     */
    public void setEffdt(Date effdt) {
        this.effdt = effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.EFFDT_STATUS
     *
     * @return the value of PS_I_DEPT.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public String getEffdtStatus() {
        return effdtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.EFFDT_STATUS
     *
     * @param effdtStatus the value for PS_I_DEPT.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public void setEffdtStatus(String effdtStatus) {
        this.effdtStatus = effdtStatus == null ? null : effdtStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.MANAGER_ID
     *
     * @return the value of PS_I_DEPT.MANAGER_ID
     *
     * @mbggenerated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.MANAGER_ID
     *
     * @param managerId the value for PS_I_DEPT.MANAGER_ID
     *
     * @mbggenerated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.MANAGER_NAME
     *
     * @return the value of PS_I_DEPT.MANAGER_NAME
     *
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.MANAGER_NAME
     *
     * @param managerName the value for PS_I_DEPT.MANAGER_NAME
     *
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.U_DEPT_LEVEL
     *
     * @return the value of PS_I_DEPT.U_DEPT_LEVEL
     *
     * @mbggenerated
     */
    public String getuDeptLevel() {
        return uDeptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.U_DEPT_LEVEL
     *
     * @param uDeptLevel the value for PS_I_DEPT.U_DEPT_LEVEL
     *
     * @mbggenerated
     */
    public void setuDeptLevel(String uDeptLevel) {
        this.uDeptLevel = uDeptLevel == null ? null : uDeptLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.UP_OID
     *
     * @return the value of PS_I_DEPT.UP_OID
     *
     * @mbggenerated
     */
    public BigDecimal getUpOid() {
        return upOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.UP_OID
     *
     * @param upOid the value for PS_I_DEPT.UP_OID
     *
     * @mbggenerated
     */
    public void setUpOid(BigDecimal upOid) {
        this.upOid = upOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.UP_DEPTID
     *
     * @return the value of PS_I_DEPT.UP_DEPTID
     *
     * @mbggenerated
     */
    public String getUpDeptid() {
        return upDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.UP_DEPTID
     *
     * @param upDeptid the value for PS_I_DEPT.UP_DEPTID
     *
     * @mbggenerated
     */
    public void setUpDeptid(String upDeptid) {
        this.upDeptid = upDeptid == null ? null : upDeptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.U_DEPT_NATURE
     *
     * @return the value of PS_I_DEPT.U_DEPT_NATURE
     *
     * @mbggenerated
     */
    public String getuDeptNature() {
        return uDeptNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.U_DEPT_NATURE
     *
     * @param uDeptNature the value for PS_I_DEPT.U_DEPT_NATURE
     *
     * @mbggenerated
     */
    public void setuDeptNature(String uDeptNature) {
        this.uDeptNature = uDeptNature == null ? null : uDeptNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.CREATIONTIME
     *
     * @return the value of PS_I_DEPT.CREATIONTIME
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.CREATIONTIME
     *
     * @param creationtime the value for PS_I_DEPT.CREATIONTIME
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.MODTIME
     *
     * @return the value of PS_I_DEPT.MODTIME
     *
     * @mbggenerated
     */
    public Date getModtime() {
        return modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.MODTIME
     *
     * @param modtime the value for PS_I_DEPT.MODTIME
     *
     * @mbggenerated
     */
    public void setModtime(Date modtime) {
        this.modtime = modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.STATUS
     *
     * @return the value of PS_I_DEPT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.STATUS
     *
     * @param status the value for PS_I_DEPT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.DEPT_ALLNAME
     *
     * @return the value of PS_I_DEPT.DEPT_ALLNAME
     *
     * @mbggenerated
     */
    public String getDeptAllname() {
        return deptAllname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.DEPT_ALLNAME
     *
     * @param deptAllname the value for PS_I_DEPT.DEPT_ALLNAME
     *
     * @mbggenerated
     */
    public void setDeptAllname(String deptAllname) {
        this.deptAllname = deptAllname == null ? null : deptAllname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.GROUP_NAME
     *
     * @return the value of PS_I_DEPT.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.GROUP_NAME
     *
     * @param groupName the value for PS_I_DEPT.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.OU
     *
     * @return the value of PS_I_DEPT.OU
     *
     * @mbggenerated
     */
    public String getOu() {
        return ou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.OU
     *
     * @param ou the value for PS_I_DEPT.OU
     *
     * @mbggenerated
     */
    public void setOu(String ou) {
        this.ou = ou == null ? null : ou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.OU_NAME
     *
     * @return the value of PS_I_DEPT.OU_NAME
     *
     * @mbggenerated
     */
    public String getOuName() {
        return ouName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.OU_NAME
     *
     * @param ouName the value for PS_I_DEPT.OU_NAME
     *
     * @mbggenerated
     */
    public void setOuName(String ouName) {
        this.ouName = ouName == null ? null : ouName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_DEPT.PS_DEPTID
     *
     * @return the value of PS_I_DEPT.PS_DEPTID
     *
     * @mbggenerated
     */
    public String getPsDeptid() {
        return psDeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_DEPT.PS_DEPTID
     *
     * @param psDeptid the value for PS_I_DEPT.PS_DEPTID
     *
     * @mbggenerated
     */
    public void setPsDeptid(String psDeptid) {
        this.psDeptid = psDeptid == null ? null : psDeptid.trim();
    }
}