package com.emrubik.rose.generator.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PS_I_EMPLOYEE
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class EmplyeePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.STAFF_NO
     *
     * @mbggenerated
     */
    private String staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.DATE_JOIN
     *
     * @mbggenerated
     */
    private Date dateJoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.STAFF_NAME
     *
     * @mbggenerated
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SECTION
     *
     * @mbggenerated
     */
    private String section;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SECTION_DESCRIPTION
     *
     * @mbggenerated
     */
    private String sectionDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SUB_SECTION
     *
     * @mbggenerated
     */
    private String subSection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SUB_DESCRIPTION
     *
     * @mbggenerated
     */
    private String subDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CITY_DESCRIPTION
     *
     * @mbggenerated
     */
    private String cityDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.BRANCH_DESCRIPTION
     *
     * @mbggenerated
     */
    private String branchDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.BRANCH
     *
     * @mbggenerated
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CORRESPONDENCE_PHONE
     *
     * @mbggenerated
     */
    private String correspondencePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.E_MAIL_ORIGINAL_COMP
     *
     * @mbggenerated
     */
    private String eMailOriginalComp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.GRADE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String gradeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SUPERVISOR_ID
     *
     * @mbggenerated
     */
    private String supervisorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.SUPERVISOR_NAME
     *
     * @mbggenerated
     */
    private String supervisorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.HR_STATUS
     *
     * @mbggenerated
     */
    private String hrStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.U_ACORD_DM_DT
     *
     * @mbggenerated
     */
    private Date uAcordDmDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.TERMINATION_DATE
     *
     * @mbggenerated
     */
    private Date terminationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.JOB_TERMINATION_DATE
     *
     * @mbggenerated
     */
    private Date jobTerminationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.NID
     *
     * @mbggenerated
     */
    private String nid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.JOB_TITLE
     *
     * @mbggenerated
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CLASS_DESCRIPTION
     *
     * @mbggenerated
     */
    private String classDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.TYPE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String typeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.DEPT_CATEGORY
     *
     * @mbggenerated
     */
    private String deptCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.EMP_LVL
     *
     * @mbggenerated
     */
    private String empLvl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.MARITAL_STATUS
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CATEGORY
     *
     * @mbggenerated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.ACCOUNT_EC_ID
     *
     * @mbggenerated
     */
    private String accountEcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.BANK_NM
     *
     * @mbggenerated
     */
    private String bankNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.EMP_CLASS
     *
     * @mbggenerated
     */
    private String empClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.EFFDT
     *
     * @mbggenerated
     */
    private Date effdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    private String effdtStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.CREATIONTIME
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.MODTIME
     *
     * @mbggenerated
     */
    private Date modtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.JOBCODE
     *
     * @mbggenerated
     */
    private String jobcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_EMPLOYEE.EFFSEQ
     *
     * @mbggenerated
     */
    private BigDecimal effseq;

    private String orgCode;

    private String orgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.STAFF_NO
     *
     * @return the value of PS_I_EMPLOYEE.STAFF_NO
     *
     * @mbggenerated
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.STAFF_NO
     *
     * @param staffNo the value for PS_I_EMPLOYEE.STAFF_NO
     *
     * @mbggenerated
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo == null ? null : staffNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.DATE_JOIN
     *
     * @return the value of PS_I_EMPLOYEE.DATE_JOIN
     *
     * @mbggenerated
     */
    public Date getDateJoin() {
        return dateJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.DATE_JOIN
     *
     * @param dateJoin the value for PS_I_EMPLOYEE.DATE_JOIN
     *
     * @mbggenerated
     */
    public void setDateJoin(Date dateJoin) {
        this.dateJoin = dateJoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.STAFF_NAME
     *
     * @return the value of PS_I_EMPLOYEE.STAFF_NAME
     *
     * @mbggenerated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.STAFF_NAME
     *
     * @param staffName the value for PS_I_EMPLOYEE.STAFF_NAME
     *
     * @mbggenerated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SECTION
     *
     * @return the value of PS_I_EMPLOYEE.SECTION
     *
     * @mbggenerated
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SECTION
     *
     * @param section the value for PS_I_EMPLOYEE.SECTION
     *
     * @mbggenerated
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SECTION_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.SECTION_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getSectionDescription() {
        return sectionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SECTION_DESCRIPTION
     *
     * @param sectionDescription the value for PS_I_EMPLOYEE.SECTION_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setSectionDescription(String sectionDescription) {
        this.sectionDescription = sectionDescription == null ? null : sectionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SUB_SECTION
     *
     * @return the value of PS_I_EMPLOYEE.SUB_SECTION
     *
     * @mbggenerated
     */
    public String getSubSection() {
        return subSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SUB_SECTION
     *
     * @param subSection the value for PS_I_EMPLOYEE.SUB_SECTION
     *
     * @mbggenerated
     */
    public void setSubSection(String subSection) {
        this.subSection = subSection == null ? null : subSection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SUB_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.SUB_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getSubDescription() {
        return subDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SUB_DESCRIPTION
     *
     * @param subDescription the value for PS_I_EMPLOYEE.SUB_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setSubDescription(String subDescription) {
        this.subDescription = subDescription == null ? null : subDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CITY
     *
     * @return the value of PS_I_EMPLOYEE.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CITY
     *
     * @param city the value for PS_I_EMPLOYEE.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CITY_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.CITY_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getCityDescription() {
        return cityDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CITY_DESCRIPTION
     *
     * @param cityDescription the value for PS_I_EMPLOYEE.CITY_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setCityDescription(String cityDescription) {
        this.cityDescription = cityDescription == null ? null : cityDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.BRANCH_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.BRANCH_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getBranchDescription() {
        return branchDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.BRANCH_DESCRIPTION
     *
     * @param branchDescription the value for PS_I_EMPLOYEE.BRANCH_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setBranchDescription(String branchDescription) {
        this.branchDescription = branchDescription == null ? null : branchDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.BRANCH
     *
     * @return the value of PS_I_EMPLOYEE.BRANCH
     *
     * @mbggenerated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.BRANCH
     *
     * @param branch the value for PS_I_EMPLOYEE.BRANCH
     *
     * @mbggenerated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.MOBILE_PHONE
     *
     * @return the value of PS_I_EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.MOBILE_PHONE
     *
     * @param mobilePhone the value for PS_I_EMPLOYEE.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CORRESPONDENCE_PHONE
     *
     * @return the value of PS_I_EMPLOYEE.CORRESPONDENCE_PHONE
     *
     * @mbggenerated
     */
    public String getCorrespondencePhone() {
        return correspondencePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CORRESPONDENCE_PHONE
     *
     * @param correspondencePhone the value for PS_I_EMPLOYEE.CORRESPONDENCE_PHONE
     *
     * @mbggenerated
     */
    public void setCorrespondencePhone(String correspondencePhone) {
        this.correspondencePhone = correspondencePhone == null ? null : correspondencePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.E_MAIL
     *
     * @return the value of PS_I_EMPLOYEE.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.E_MAIL
     *
     * @param eMail the value for PS_I_EMPLOYEE.E_MAIL
     *
     * @mbggenerated
     */
    public void seteMail(String eMail) {
        this.eMail = eMail == null ? null : eMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.E_MAIL_ORIGINAL_COMP
     *
     * @return the value of PS_I_EMPLOYEE.E_MAIL_ORIGINAL_COMP
     *
     * @mbggenerated
     */
    public String geteMailOriginalComp() {
        return eMailOriginalComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.E_MAIL_ORIGINAL_COMP
     *
     * @param eMailOriginalComp the value for PS_I_EMPLOYEE.E_MAIL_ORIGINAL_COMP
     *
     * @mbggenerated
     */
    public void seteMailOriginalComp(String eMailOriginalComp) {
        this.eMailOriginalComp = eMailOriginalComp == null ? null : eMailOriginalComp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SEX
     *
     * @return the value of PS_I_EMPLOYEE.SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SEX
     *
     * @param sex the value for PS_I_EMPLOYEE.SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.GRADE_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.GRADE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getGradeDescription() {
        return gradeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.GRADE_DESCRIPTION
     *
     * @param gradeDescription the value for PS_I_EMPLOYEE.GRADE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setGradeDescription(String gradeDescription) {
        this.gradeDescription = gradeDescription == null ? null : gradeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SUPERVISOR_ID
     *
     * @return the value of PS_I_EMPLOYEE.SUPERVISOR_ID
     *
     * @mbggenerated
     */
    public String getSupervisorId() {
        return supervisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SUPERVISOR_ID
     *
     * @param supervisorId the value for PS_I_EMPLOYEE.SUPERVISOR_ID
     *
     * @mbggenerated
     */
    public void setSupervisorId(String supervisorId) {
        this.supervisorId = supervisorId == null ? null : supervisorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.SUPERVISOR_NAME
     *
     * @return the value of PS_I_EMPLOYEE.SUPERVISOR_NAME
     *
     * @mbggenerated
     */
    public String getSupervisorName() {
        return supervisorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.SUPERVISOR_NAME
     *
     * @param supervisorName the value for PS_I_EMPLOYEE.SUPERVISOR_NAME
     *
     * @mbggenerated
     */
    public void setSupervisorName(String supervisorName) {
        this.supervisorName = supervisorName == null ? null : supervisorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.HR_STATUS
     *
     * @return the value of PS_I_EMPLOYEE.HR_STATUS
     *
     * @mbggenerated
     */
    public String getHrStatus() {
        return hrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.HR_STATUS
     *
     * @param hrStatus the value for PS_I_EMPLOYEE.HR_STATUS
     *
     * @mbggenerated
     */
    public void setHrStatus(String hrStatus) {
        this.hrStatus = hrStatus == null ? null : hrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.DATE_OF_BIRTH
     *
     * @return the value of PS_I_EMPLOYEE.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for PS_I_EMPLOYEE.DATE_OF_BIRTH
     *
     * @mbggenerated
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.U_ACORD_DM_DT
     *
     * @return the value of PS_I_EMPLOYEE.U_ACORD_DM_DT
     *
     * @mbggenerated
     */
    public Date getuAcordDmDt() {
        return uAcordDmDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.U_ACORD_DM_DT
     *
     * @param uAcordDmDt the value for PS_I_EMPLOYEE.U_ACORD_DM_DT
     *
     * @mbggenerated
     */
    public void setuAcordDmDt(Date uAcordDmDt) {
        this.uAcordDmDt = uAcordDmDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.TERMINATION_DATE
     *
     * @return the value of PS_I_EMPLOYEE.TERMINATION_DATE
     *
     * @mbggenerated
     */
    public Date getTerminationDate() {
        return terminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.TERMINATION_DATE
     *
     * @param terminationDate the value for PS_I_EMPLOYEE.TERMINATION_DATE
     *
     * @mbggenerated
     */
    public void setTerminationDate(Date terminationDate) {
        this.terminationDate = terminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.JOB_TERMINATION_DATE
     *
     * @return the value of PS_I_EMPLOYEE.JOB_TERMINATION_DATE
     *
     * @mbggenerated
     */
    public Date getJobTerminationDate() {
        return jobTerminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.JOB_TERMINATION_DATE
     *
     * @param jobTerminationDate the value for PS_I_EMPLOYEE.JOB_TERMINATION_DATE
     *
     * @mbggenerated
     */
    public void setJobTerminationDate(Date jobTerminationDate) {
        this.jobTerminationDate = jobTerminationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.NID
     *
     * @return the value of PS_I_EMPLOYEE.NID
     *
     * @mbggenerated
     */
    public String getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.NID
     *
     * @param nid the value for PS_I_EMPLOYEE.NID
     *
     * @mbggenerated
     */
    public void setNid(String nid) {
        this.nid = nid == null ? null : nid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.JOB_TITLE
     *
     * @return the value of PS_I_EMPLOYEE.JOB_TITLE
     *
     * @mbggenerated
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.JOB_TITLE
     *
     * @param jobTitle the value for PS_I_EMPLOYEE.JOB_TITLE
     *
     * @mbggenerated
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CLASS_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.CLASS_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getClassDescription() {
        return classDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CLASS_DESCRIPTION
     *
     * @param classDescription the value for PS_I_EMPLOYEE.CLASS_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setClassDescription(String classDescription) {
        this.classDescription = classDescription == null ? null : classDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.TYPE_DESCRIPTION
     *
     * @return the value of PS_I_EMPLOYEE.TYPE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getTypeDescription() {
        return typeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.TYPE_DESCRIPTION
     *
     * @param typeDescription the value for PS_I_EMPLOYEE.TYPE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription == null ? null : typeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.DEPT_CATEGORY
     *
     * @return the value of PS_I_EMPLOYEE.DEPT_CATEGORY
     *
     * @mbggenerated
     */
    public String getDeptCategory() {
        return deptCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.DEPT_CATEGORY
     *
     * @param deptCategory the value for PS_I_EMPLOYEE.DEPT_CATEGORY
     *
     * @mbggenerated
     */
    public void setDeptCategory(String deptCategory) {
        this.deptCategory = deptCategory == null ? null : deptCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.GROUP_NAME
     *
     * @return the value of PS_I_EMPLOYEE.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.GROUP_NAME
     *
     * @param groupName the value for PS_I_EMPLOYEE.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.EMP_LVL
     *
     * @return the value of PS_I_EMPLOYEE.EMP_LVL
     *
     * @mbggenerated
     */
    public String getEmpLvl() {
        return empLvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.EMP_LVL
     *
     * @param empLvl the value for PS_I_EMPLOYEE.EMP_LVL
     *
     * @mbggenerated
     */
    public void setEmpLvl(String empLvl) {
        this.empLvl = empLvl == null ? null : empLvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.MARITAL_STATUS
     *
     * @return the value of PS_I_EMPLOYEE.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.MARITAL_STATUS
     *
     * @param maritalStatus the value for PS_I_EMPLOYEE.MARITAL_STATUS
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CATEGORY
     *
     * @return the value of PS_I_EMPLOYEE.CATEGORY
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CATEGORY
     *
     * @param category the value for PS_I_EMPLOYEE.CATEGORY
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.ACCOUNT_NAME
     *
     * @return the value of PS_I_EMPLOYEE.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.ACCOUNT_NAME
     *
     * @param accountName the value for PS_I_EMPLOYEE.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.ACCOUNT_EC_ID
     *
     * @return the value of PS_I_EMPLOYEE.ACCOUNT_EC_ID
     *
     * @mbggenerated
     */
    public String getAccountEcId() {
        return accountEcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.ACCOUNT_EC_ID
     *
     * @param accountEcId the value for PS_I_EMPLOYEE.ACCOUNT_EC_ID
     *
     * @mbggenerated
     */
    public void setAccountEcId(String accountEcId) {
        this.accountEcId = accountEcId == null ? null : accountEcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.BANK_NM
     *
     * @return the value of PS_I_EMPLOYEE.BANK_NM
     *
     * @mbggenerated
     */
    public String getBankNm() {
        return bankNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.BANK_NM
     *
     * @param bankNm the value for PS_I_EMPLOYEE.BANK_NM
     *
     * @mbggenerated
     */
    public void setBankNm(String bankNm) {
        this.bankNm = bankNm == null ? null : bankNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.EMP_CLASS
     *
     * @return the value of PS_I_EMPLOYEE.EMP_CLASS
     *
     * @mbggenerated
     */
    public String getEmpClass() {
        return empClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.EMP_CLASS
     *
     * @param empClass the value for PS_I_EMPLOYEE.EMP_CLASS
     *
     * @mbggenerated
     */
    public void setEmpClass(String empClass) {
        this.empClass = empClass == null ? null : empClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.EFFDT
     *
     * @return the value of PS_I_EMPLOYEE.EFFDT
     *
     * @mbggenerated
     */
    public Date getEffdt() {
        return effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.EFFDT
     *
     * @param effdt the value for PS_I_EMPLOYEE.EFFDT
     *
     * @mbggenerated
     */
    public void setEffdt(Date effdt) {
        this.effdt = effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.EFFDT_STATUS
     *
     * @return the value of PS_I_EMPLOYEE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public String getEffdtStatus() {
        return effdtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.EFFDT_STATUS
     *
     * @param effdtStatus the value for PS_I_EMPLOYEE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public void setEffdtStatus(String effdtStatus) {
        this.effdtStatus = effdtStatus == null ? null : effdtStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.CREATIONTIME
     *
     * @return the value of PS_I_EMPLOYEE.CREATIONTIME
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.CREATIONTIME
     *
     * @param creationtime the value for PS_I_EMPLOYEE.CREATIONTIME
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.MODTIME
     *
     * @return the value of PS_I_EMPLOYEE.MODTIME
     *
     * @mbggenerated
     */
    public Date getModtime() {
        return modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.MODTIME
     *
     * @param modtime the value for PS_I_EMPLOYEE.MODTIME
     *
     * @mbggenerated
     */
    public void setModtime(Date modtime) {
        this.modtime = modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.JOBCODE
     *
     * @return the value of PS_I_EMPLOYEE.JOBCODE
     *
     * @mbggenerated
     */
    public String getJobcode() {
        return jobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.JOBCODE
     *
     * @param jobcode the value for PS_I_EMPLOYEE.JOBCODE
     *
     * @mbggenerated
     */
    public void setJobcode(String jobcode) {
        this.jobcode = jobcode == null ? null : jobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_EMPLOYEE.EFFSEQ
     *
     * @return the value of PS_I_EMPLOYEE.EFFSEQ
     *
     * @mbggenerated
     */
    public BigDecimal getEffseq() {
        return effseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_EMPLOYEE.EFFSEQ
     *
     * @param effseq the value for PS_I_EMPLOYEE.EFFSEQ
     *
     * @mbggenerated
     */
    public void setEffseq(BigDecimal effseq) {
        this.effseq = effseq;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
}