package com.emrubik.rose.generator.dao.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PS_I_JOBCODE
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class JobCodePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.OID
     *
     * @mbggenerated
     */
    private BigDecimal oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.JOBCODE
     *
     * @mbggenerated
     */
    private String jobcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.DESCR
     *
     * @mbggenerated
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.EFFDT
     *
     * @mbggenerated
     */
    private Date effdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    private String effdtStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.CREATIONTIME
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.MODTIME
     *
     * @mbggenerated
     */
    private Date modtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_JOBCODE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.OID
     *
     * @return the value of PS_I_JOBCODE.OID
     *
     * @mbggenerated
     */
    public BigDecimal getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.OID
     *
     * @param oid the value for PS_I_JOBCODE.OID
     *
     * @mbggenerated
     */
    public void setOid(BigDecimal oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.JOBCODE
     *
     * @return the value of PS_I_JOBCODE.JOBCODE
     *
     * @mbggenerated
     */
    public String getJobcode() {
        return jobcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.JOBCODE
     *
     * @param jobcode the value for PS_I_JOBCODE.JOBCODE
     *
     * @mbggenerated
     */
    public void setJobcode(String jobcode) {
        this.jobcode = jobcode == null ? null : jobcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.DESCR
     *
     * @return the value of PS_I_JOBCODE.DESCR
     *
     * @mbggenerated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.DESCR
     *
     * @param descr the value for PS_I_JOBCODE.DESCR
     *
     * @mbggenerated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.EFFDT
     *
     * @return the value of PS_I_JOBCODE.EFFDT
     *
     * @mbggenerated
     */
    public Date getEffdt() {
        return effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.EFFDT
     *
     * @param effdt the value for PS_I_JOBCODE.EFFDT
     *
     * @mbggenerated
     */
    public void setEffdt(Date effdt) {
        this.effdt = effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.EFFDT_STATUS
     *
     * @return the value of PS_I_JOBCODE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public String getEffdtStatus() {
        return effdtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.EFFDT_STATUS
     *
     * @param effdtStatus the value for PS_I_JOBCODE.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public void setEffdtStatus(String effdtStatus) {
        this.effdtStatus = effdtStatus == null ? null : effdtStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.CREATIONTIME
     *
     * @return the value of PS_I_JOBCODE.CREATIONTIME
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.CREATIONTIME
     *
     * @param creationtime the value for PS_I_JOBCODE.CREATIONTIME
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.MODTIME
     *
     * @return the value of PS_I_JOBCODE.MODTIME
     *
     * @mbggenerated
     */
    public Date getModtime() {
        return modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.MODTIME
     *
     * @param modtime the value for PS_I_JOBCODE.MODTIME
     *
     * @mbggenerated
     */
    public void setModtime(Date modtime) {
        this.modtime = modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_JOBCODE.STATUS
     *
     * @return the value of PS_I_JOBCODE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_JOBCODE.STATUS
     *
     * @param status the value for PS_I_JOBCODE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}