package com.emrubik.rose.generator.dao.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoseWorkflowPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public RoseWorkflowPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorkflowcodeIsNull() {
            addCriterion("WORKFLOWCODE is null");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeIsNotNull() {
            addCriterion("WORKFLOWCODE is not null");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeEqualTo(String value) {
            addCriterion("WORKFLOWCODE =", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeNotEqualTo(String value) {
            addCriterion("WORKFLOWCODE <>", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeGreaterThan(String value) {
            addCriterion("WORKFLOWCODE >", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeGreaterThanOrEqualTo(String value) {
            addCriterion("WORKFLOWCODE >=", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeLessThan(String value) {
            addCriterion("WORKFLOWCODE <", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeLessThanOrEqualTo(String value) {
            addCriterion("WORKFLOWCODE <=", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeLike(String value) {
            addCriterion("WORKFLOWCODE like", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeNotLike(String value) {
            addCriterion("WORKFLOWCODE not like", value, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeIn(List<String> values) {
            addCriterion("WORKFLOWCODE in", values, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeNotIn(List<String> values) {
            addCriterion("WORKFLOWCODE not in", values, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeBetween(String value1, String value2) {
            addCriterion("WORKFLOWCODE between", value1, value2, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andWorkflowcodeNotBetween(String value1, String value2) {
            addCriterion("WORKFLOWCODE not between", value1, value2, "workflowcode");
            return (Criteria) this;
        }

        public Criteria andEmpidIsNull() {
            addCriterion("EMPID is null");
            return (Criteria) this;
        }

        public Criteria andEmpidIsNotNull() {
            addCriterion("EMPID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpidEqualTo(String value) {
            addCriterion("EMPID =", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidNotEqualTo(String value) {
            addCriterion("EMPID <>", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidGreaterThan(String value) {
            addCriterion("EMPID >", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidGreaterThanOrEqualTo(String value) {
            addCriterion("EMPID >=", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidLessThan(String value) {
            addCriterion("EMPID <", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidLessThanOrEqualTo(String value) {
            addCriterion("EMPID <=", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidLike(String value) {
            addCriterion("EMPID like", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidNotLike(String value) {
            addCriterion("EMPID not like", value, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidIn(List<String> values) {
            addCriterion("EMPID in", values, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidNotIn(List<String> values) {
            addCriterion("EMPID not in", values, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidBetween(String value1, String value2) {
            addCriterion("EMPID between", value1, value2, "empid");
            return (Criteria) this;
        }

        public Criteria andEmpidNotBetween(String value1, String value2) {
            addCriterion("EMPID not between", value1, value2, "empid");
            return (Criteria) this;
        }

        public Criteria andEffdtIsNull() {
            addCriterion("EFFDT is null");
            return (Criteria) this;
        }

        public Criteria andEffdtIsNotNull() {
            addCriterion("EFFDT is not null");
            return (Criteria) this;
        }

        public Criteria andEffdtEqualTo(Date value) {
            addCriterion("EFFDT =", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotEqualTo(Date value) {
            addCriterion("EFFDT <>", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtGreaterThan(Date value) {
            addCriterion("EFFDT >", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtGreaterThanOrEqualTo(Date value) {
            addCriterion("EFFDT >=", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtLessThan(Date value) {
            addCriterion("EFFDT <", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtLessThanOrEqualTo(Date value) {
            addCriterion("EFFDT <=", value, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtIn(List<Date> values) {
            addCriterion("EFFDT in", values, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotIn(List<Date> values) {
            addCriterion("EFFDT not in", values, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtBetween(Date value1, Date value2) {
            addCriterion("EFFDT between", value1, value2, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtNotBetween(Date value1, Date value2) {
            addCriterion("EFFDT not between", value1, value2, "effdt");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIsNull() {
            addCriterion("EFFDT_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIsNotNull() {
            addCriterion("EFFDT_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusEqualTo(String value) {
            addCriterion("EFFDT_STATUS =", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotEqualTo(String value) {
            addCriterion("EFFDT_STATUS <>", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusGreaterThan(String value) {
            addCriterion("EFFDT_STATUS >", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusGreaterThanOrEqualTo(String value) {
            addCriterion("EFFDT_STATUS >=", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLessThan(String value) {
            addCriterion("EFFDT_STATUS <", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLessThanOrEqualTo(String value) {
            addCriterion("EFFDT_STATUS <=", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusLike(String value) {
            addCriterion("EFFDT_STATUS like", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotLike(String value) {
            addCriterion("EFFDT_STATUS not like", value, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusIn(List<String> values) {
            addCriterion("EFFDT_STATUS in", values, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotIn(List<String> values) {
            addCriterion("EFFDT_STATUS not in", values, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusBetween(String value1, String value2) {
            addCriterion("EFFDT_STATUS between", value1, value2, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andEffdtStatusNotBetween(String value1, String value2) {
            addCriterion("EFFDT_STATUS not between", value1, value2, "effdtStatus");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNull() {
            addCriterion("CREATIONTIME is null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNotNull() {
            addCriterion("CREATIONTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeEqualTo(Date value) {
            addCriterion("CREATIONTIME =", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotEqualTo(Date value) {
            addCriterion("CREATIONTIME <>", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThan(Date value) {
            addCriterion("CREATIONTIME >", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME >=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThan(Date value) {
            addCriterion("CREATIONTIME <", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME <=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIn(List<Date> values) {
            addCriterion("CREATIONTIME in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotIn(List<Date> values) {
            addCriterion("CREATIONTIME not in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME not between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNull() {
            addCriterion("MODTIME is null");
            return (Criteria) this;
        }

        public Criteria andModtimeIsNotNull() {
            addCriterion("MODTIME is not null");
            return (Criteria) this;
        }

        public Criteria andModtimeEqualTo(Date value) {
            addCriterion("MODTIME =", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotEqualTo(Date value) {
            addCriterion("MODTIME <>", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThan(Date value) {
            addCriterion("MODTIME >", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODTIME >=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThan(Date value) {
            addCriterion("MODTIME <", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeLessThanOrEqualTo(Date value) {
            addCriterion("MODTIME <=", value, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeIn(List<Date> values) {
            addCriterion("MODTIME in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotIn(List<Date> values) {
            addCriterion("MODTIME not in", values, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeBetween(Date value1, Date value2) {
            addCriterion("MODTIME between", value1, value2, "modtime");
            return (Criteria) this;
        }

        public Criteria andModtimeNotBetween(Date value1, Date value2) {
            addCriterion("MODTIME not between", value1, value2, "modtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PS_I_ROSE_WORKFLOW
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}