package com.emrubik.rose.generator.dao.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PS_I_ROSE_WORKFLOW
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class RoseWorkflowPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.WORKFLOWCODE
     *
     * @mbggenerated
     */
    private String workflowcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.EMPID
     *
     * @mbggenerated
     */
    private String empid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.EFFDT
     *
     * @mbggenerated
     */
    private Date effdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.EFFDT_STATUS
     *
     * @mbggenerated
     */
    private String effdtStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.CREATIONTIME
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.MODTIME
     *
     * @mbggenerated
     */
    private Date modtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PS_I_ROSE_WORKFLOW.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.WORKFLOWCODE
     *
     * @return the value of PS_I_ROSE_WORKFLOW.WORKFLOWCODE
     *
     * @mbggenerated
     */
    public String getWorkflowcode() {
        return workflowcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.WORKFLOWCODE
     *
     * @param workflowcode the value for PS_I_ROSE_WORKFLOW.WORKFLOWCODE
     *
     * @mbggenerated
     */
    public void setWorkflowcode(String workflowcode) {
        this.workflowcode = workflowcode == null ? null : workflowcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.EMPID
     *
     * @return the value of PS_I_ROSE_WORKFLOW.EMPID
     *
     * @mbggenerated
     */
    public String getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.EMPID
     *
     * @param empid the value for PS_I_ROSE_WORKFLOW.EMPID
     *
     * @mbggenerated
     */
    public void setEmpid(String empid) {
        this.empid = empid == null ? null : empid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.EFFDT
     *
     * @return the value of PS_I_ROSE_WORKFLOW.EFFDT
     *
     * @mbggenerated
     */
    public Date getEffdt() {
        return effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.EFFDT
     *
     * @param effdt the value for PS_I_ROSE_WORKFLOW.EFFDT
     *
     * @mbggenerated
     */
    public void setEffdt(Date effdt) {
        this.effdt = effdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.EFFDT_STATUS
     *
     * @return the value of PS_I_ROSE_WORKFLOW.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public String getEffdtStatus() {
        return effdtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.EFFDT_STATUS
     *
     * @param effdtStatus the value for PS_I_ROSE_WORKFLOW.EFFDT_STATUS
     *
     * @mbggenerated
     */
    public void setEffdtStatus(String effdtStatus) {
        this.effdtStatus = effdtStatus == null ? null : effdtStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.CREATIONTIME
     *
     * @return the value of PS_I_ROSE_WORKFLOW.CREATIONTIME
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.CREATIONTIME
     *
     * @param creationtime the value for PS_I_ROSE_WORKFLOW.CREATIONTIME
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.MODTIME
     *
     * @return the value of PS_I_ROSE_WORKFLOW.MODTIME
     *
     * @mbggenerated
     */
    public Date getModtime() {
        return modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.MODTIME
     *
     * @param modtime the value for PS_I_ROSE_WORKFLOW.MODTIME
     *
     * @mbggenerated
     */
    public void setModtime(Date modtime) {
        this.modtime = modtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PS_I_ROSE_WORKFLOW.STATUS
     *
     * @return the value of PS_I_ROSE_WORKFLOW.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PS_I_ROSE_WORKFLOW.STATUS
     *
     * @param status the value for PS_I_ROSE_WORKFLOW.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}