package com.emrubik.rosemail.generator.dao;

import com.emrubik.rosemail.generator.dao.bean.PssEmailPo;
import com.emrubik.rosemail.generator.dao.bean.PssEmailPoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PssEmailPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int countByExample(PssEmailPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int deleteByExample(PssEmailPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("moid") BigDecimal moid, @Param("mailto") String mailto, @Param("mtitle") String mtitle, @Param("mtext") String mtext);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int insert(PssEmailPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int insertSelective(PssEmailPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    List<PssEmailPo> selectByExample(PssEmailPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    PssEmailPo selectByPrimaryKey(@Param("moid") BigDecimal moid, @Param("mailto") String mailto, @Param("mtitle") String mtitle, @Param("mtext") String mtext);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PssEmailPo record, @Param("example") PssEmailPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PssEmailPo record, @Param("example") PssEmailPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PssEmailPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PssEmailPo record);
}