package com.emrubik.rosemail.generator.dao.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PssEmailPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public PssEmailPoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMoidIsNull() {
            addCriterion("MOID is null");
            return (Criteria) this;
        }

        public Criteria andMoidIsNotNull() {
            addCriterion("MOID is not null");
            return (Criteria) this;
        }

        public Criteria andMoidEqualTo(BigDecimal value) {
            addCriterion("MOID =", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidNotEqualTo(BigDecimal value) {
            addCriterion("MOID <>", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidGreaterThan(BigDecimal value) {
            addCriterion("MOID >", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MOID >=", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidLessThan(BigDecimal value) {
            addCriterion("MOID <", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MOID <=", value, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidIn(List<BigDecimal> values) {
            addCriterion("MOID in", values, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidNotIn(List<BigDecimal> values) {
            addCriterion("MOID not in", values, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOID between", value1, value2, "moid");
            return (Criteria) this;
        }

        public Criteria andMoidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOID not between", value1, value2, "moid");
            return (Criteria) this;
        }

        public Criteria andMailtoIsNull() {
            addCriterion("MAILTO is null");
            return (Criteria) this;
        }

        public Criteria andMailtoIsNotNull() {
            addCriterion("MAILTO is not null");
            return (Criteria) this;
        }

        public Criteria andMailtoEqualTo(String value) {
            addCriterion("MAILTO =", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoNotEqualTo(String value) {
            addCriterion("MAILTO <>", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoGreaterThan(String value) {
            addCriterion("MAILTO >", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoGreaterThanOrEqualTo(String value) {
            addCriterion("MAILTO >=", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoLessThan(String value) {
            addCriterion("MAILTO <", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoLessThanOrEqualTo(String value) {
            addCriterion("MAILTO <=", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoLike(String value) {
            addCriterion("MAILTO like", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoNotLike(String value) {
            addCriterion("MAILTO not like", value, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoIn(List<String> values) {
            addCriterion("MAILTO in", values, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoNotIn(List<String> values) {
            addCriterion("MAILTO not in", values, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoBetween(String value1, String value2) {
            addCriterion("MAILTO between", value1, value2, "mailto");
            return (Criteria) this;
        }

        public Criteria andMailtoNotBetween(String value1, String value2) {
            addCriterion("MAILTO not between", value1, value2, "mailto");
            return (Criteria) this;
        }

        public Criteria andMtitleIsNull() {
            addCriterion("MTITLE is null");
            return (Criteria) this;
        }

        public Criteria andMtitleIsNotNull() {
            addCriterion("MTITLE is not null");
            return (Criteria) this;
        }

        public Criteria andMtitleEqualTo(String value) {
            addCriterion("MTITLE =", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleNotEqualTo(String value) {
            addCriterion("MTITLE <>", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleGreaterThan(String value) {
            addCriterion("MTITLE >", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleGreaterThanOrEqualTo(String value) {
            addCriterion("MTITLE >=", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleLessThan(String value) {
            addCriterion("MTITLE <", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleLessThanOrEqualTo(String value) {
            addCriterion("MTITLE <=", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleLike(String value) {
            addCriterion("MTITLE like", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleNotLike(String value) {
            addCriterion("MTITLE not like", value, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleIn(List<String> values) {
            addCriterion("MTITLE in", values, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleNotIn(List<String> values) {
            addCriterion("MTITLE not in", values, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleBetween(String value1, String value2) {
            addCriterion("MTITLE between", value1, value2, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtitleNotBetween(String value1, String value2) {
            addCriterion("MTITLE not between", value1, value2, "mtitle");
            return (Criteria) this;
        }

        public Criteria andMtextIsNull() {
            addCriterion("MTEXT is null");
            return (Criteria) this;
        }

        public Criteria andMtextIsNotNull() {
            addCriterion("MTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andMtextEqualTo(String value) {
            addCriterion("MTEXT =", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextNotEqualTo(String value) {
            addCriterion("MTEXT <>", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextGreaterThan(String value) {
            addCriterion("MTEXT >", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextGreaterThanOrEqualTo(String value) {
            addCriterion("MTEXT >=", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextLessThan(String value) {
            addCriterion("MTEXT <", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextLessThanOrEqualTo(String value) {
            addCriterion("MTEXT <=", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextLike(String value) {
            addCriterion("MTEXT like", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextNotLike(String value) {
            addCriterion("MTEXT not like", value, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextIn(List<String> values) {
            addCriterion("MTEXT in", values, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextNotIn(List<String> values) {
            addCriterion("MTEXT not in", values, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextBetween(String value1, String value2) {
            addCriterion("MTEXT between", value1, value2, "mtext");
            return (Criteria) this;
        }

        public Criteria andMtextNotBetween(String value1, String value2) {
            addCriterion("MTEXT not between", value1, value2, "mtext");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("STARTTIME is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("STARTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(String value) {
            addCriterion("STARTTIME =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(String value) {
            addCriterion("STARTTIME <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(String value) {
            addCriterion("STARTTIME >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(String value) {
            addCriterion("STARTTIME >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(String value) {
            addCriterion("STARTTIME <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(String value) {
            addCriterion("STARTTIME <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLike(String value) {
            addCriterion("STARTTIME like", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotLike(String value) {
            addCriterion("STARTTIME not like", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<String> values) {
            addCriterion("STARTTIME in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<String> values) {
            addCriterion("STARTTIME not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(String value1, String value2) {
            addCriterion("STARTTIME between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(String value1, String value2) {
            addCriterion("STARTTIME not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("ENDTIME is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("ENDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(String value) {
            addCriterion("ENDTIME =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(String value) {
            addCriterion("ENDTIME <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(String value) {
            addCriterion("ENDTIME >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ENDTIME >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(String value) {
            addCriterion("ENDTIME <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(String value) {
            addCriterion("ENDTIME <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLike(String value) {
            addCriterion("ENDTIME like", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotLike(String value) {
            addCriterion("ENDTIME not like", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<String> values) {
            addCriterion("ENDTIME in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<String> values) {
            addCriterion("ENDTIME not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(String value1, String value2) {
            addCriterion("ENDTIME between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(String value1, String value2) {
            addCriterion("ENDTIME not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andSendflagIsNull() {
            addCriterion("SENDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andSendflagIsNotNull() {
            addCriterion("SENDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSendflagEqualTo(BigDecimal value) {
            addCriterion("SENDFLAG =", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagNotEqualTo(BigDecimal value) {
            addCriterion("SENDFLAG <>", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagGreaterThan(BigDecimal value) {
            addCriterion("SENDFLAG >", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SENDFLAG >=", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagLessThan(BigDecimal value) {
            addCriterion("SENDFLAG <", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SENDFLAG <=", value, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagIn(List<BigDecimal> values) {
            addCriterion("SENDFLAG in", values, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagNotIn(List<BigDecimal> values) {
            addCriterion("SENDFLAG not in", values, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SENDFLAG between", value1, value2, "sendflag");
            return (Criteria) this;
        }

        public Criteria andSendflagNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SENDFLAG not between", value1, value2, "sendflag");
            return (Criteria) this;
        }

        public Criteria andStrappdef1IsNull() {
            addCriterion("STRAPPDEF1 is null");
            return (Criteria) this;
        }

        public Criteria andStrappdef1IsNotNull() {
            addCriterion("STRAPPDEF1 is not null");
            return (Criteria) this;
        }

        public Criteria andStrappdef1EqualTo(String value) {
            addCriterion("STRAPPDEF1 =", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1NotEqualTo(String value) {
            addCriterion("STRAPPDEF1 <>", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1GreaterThan(String value) {
            addCriterion("STRAPPDEF1 >", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1GreaterThanOrEqualTo(String value) {
            addCriterion("STRAPPDEF1 >=", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1LessThan(String value) {
            addCriterion("STRAPPDEF1 <", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1LessThanOrEqualTo(String value) {
            addCriterion("STRAPPDEF1 <=", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1Like(String value) {
            addCriterion("STRAPPDEF1 like", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1NotLike(String value) {
            addCriterion("STRAPPDEF1 not like", value, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1In(List<String> values) {
            addCriterion("STRAPPDEF1 in", values, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1NotIn(List<String> values) {
            addCriterion("STRAPPDEF1 not in", values, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1Between(String value1, String value2) {
            addCriterion("STRAPPDEF1 between", value1, value2, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef1NotBetween(String value1, String value2) {
            addCriterion("STRAPPDEF1 not between", value1, value2, "strappdef1");
            return (Criteria) this;
        }

        public Criteria andStrappdef2IsNull() {
            addCriterion("STRAPPDEF2 is null");
            return (Criteria) this;
        }

        public Criteria andStrappdef2IsNotNull() {
            addCriterion("STRAPPDEF2 is not null");
            return (Criteria) this;
        }

        public Criteria andStrappdef2EqualTo(String value) {
            addCriterion("STRAPPDEF2 =", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2NotEqualTo(String value) {
            addCriterion("STRAPPDEF2 <>", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2GreaterThan(String value) {
            addCriterion("STRAPPDEF2 >", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2GreaterThanOrEqualTo(String value) {
            addCriterion("STRAPPDEF2 >=", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2LessThan(String value) {
            addCriterion("STRAPPDEF2 <", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2LessThanOrEqualTo(String value) {
            addCriterion("STRAPPDEF2 <=", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2Like(String value) {
            addCriterion("STRAPPDEF2 like", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2NotLike(String value) {
            addCriterion("STRAPPDEF2 not like", value, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2In(List<String> values) {
            addCriterion("STRAPPDEF2 in", values, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2NotIn(List<String> values) {
            addCriterion("STRAPPDEF2 not in", values, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2Between(String value1, String value2) {
            addCriterion("STRAPPDEF2 between", value1, value2, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andStrappdef2NotBetween(String value1, String value2) {
            addCriterion("STRAPPDEF2 not between", value1, value2, "strappdef2");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNull() {
            addCriterion("CREATIONTIME is null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNotNull() {
            addCriterion("CREATIONTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeEqualTo(Date value) {
            addCriterion("CREATIONTIME =", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotEqualTo(Date value) {
            addCriterion("CREATIONTIME <>", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThan(Date value) {
            addCriterion("CREATIONTIME >", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME >=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThan(Date value) {
            addCriterion("CREATIONTIME <", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATIONTIME <=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIn(List<Date> values) {
            addCriterion("CREATIONTIME in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotIn(List<Date> values) {
            addCriterion("CREATIONTIME not in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATIONTIME not between", value1, value2, "creationtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UEC_PSS_EMAIL
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}